name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test
    env:
      GO111MODULE: "on",
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: make test